source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'FirebaseRemoteSettings_Example' do
  pod 'FirebaseRemoteSettings', :path => '../'
  
  pod 'CoreRemoteSettings/RxSwift'
  pod 'Firebase'

  target 'FirebaseRemoteSettings_Tests' do
    inherit! :search_paths

    
  end
end
